# Generated by Django 2.0.1 on 2018-01-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_remove_move_by_first_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
